version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: personalityDB
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: root_password
      DB_NAME: personalityDB
    depends_on:
      - db
  frontend:
    build: ../personality-test-ui/
    image: personality-test-ui
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BASE_API_URL: http://localhost:8080
volumes:
  mysql_data:
